import assert from "node:assert/strict";
import { readFileSync } from "node:fs";

const html = readFileSync("frontend/index.html", "utf8");
const css = readFileSync("frontend/index.css", "utf8");
const js = readFileSync("frontend/index.js", "utf8");

assert.match(html, /id="status-toggle-button"/, "status toggle button should exist");
assert.match(html, /aria-controls="status-panel"/, "status toggle should target status panel");
assert.match(html, /id="scene-background-image"/, "scene background should use a real image element for large data URLs");
assert.match(html, /id="login-help"/, "friend playtest login help should exist");
assert.match(html, /id="login-status"/, "login loading status should exist");
assert.match(html, /id="connection-banner"/, "inline connection banner should exist");
assert.match(html, /id="action-status"/, "action availability status should exist");
assert.doesNotMatch(html, /id="fullscreen-button"/, "fullscreen button should be removed");

assert.match(css, /#app-container\s*{[^}]*height:\s*100vh/s, "app should default to viewport height");
assert.match(css, /#app-container\s*{[^}]*max-width:\s*none/s, "app should default to full viewport width");
assert.match(css, /#game-view\.status-collapsed\s*{[^}]*grid-template-columns:\s*48px\s+1fr/s, "desktop collapsed status rail should keep the status panel on the left");
assert.match(css, /#connection-banner\s*{[^}]*grid-area:\s*connection/s, "connection banner should own a stable grid row");
assert.match(css, /\.connection-reconnecting::before/, "reconnecting state should have a visible connection indicator");
assert.match(css, /\.connection-sending::before/, "sending state should have a visible connection indicator");
assert.match(css, /\.action-status\s*{[^}]*min-height:/s, "action status text should reserve stable space");
assert.match(css, /#login-form input:disabled\s*{[^}]*cursor:\s*not-allowed/s, "login inputs should look disabled while submitting");
assert.match(css, /@media\s*\(max-width:\s*850px\)[\s\S]*#status-panel\s*{[^}]*position:\s*absolute/s, "mobile status panel should overlay instead of consuming layout rows");
assert.match(css, /@media\s*\(max-width:\s*850px\)[\s\S]*#game-view\.status-collapsed\s+#status-panel/s, "mobile collapsed status panel should be hidden off-canvas");
assert.match(css, /#scene-background-image\s*{[^}]*position:\s*fixed/s, "scene background image should be fixed behind the app");
assert.match(css, /#scene-background-image\s*{[^}]*pointer-events:\s*none/s, "scene background image must not block clicks or input");
assert.match(css, /#scene-background-image\s*{[^}]*z-index:\s*2/s, "scene background image should visually sit above the app");
assert.match(css, /body\.has-scene-background\s+#scene-background-image\s*{[^}]*opacity:\s*0\.2/s, "scene background should render at 0.20 opacity");
assert.match(css, /#app-container\s*{[^}]*z-index:\s*1/s, "app content should render above the scene background layer");

assert.match(js, /statusToggleButton:\s*document\.getElementById\('status-toggle-button'\)/, "status toggle should be wired in DOMElements");
assert.match(js, /connectionBanner:\s*document\.getElementById\('connection-banner'\)/, "connection banner should be wired in DOMElements");
assert.match(js, /actionStatus:\s*document\.getElementById\('action-status'\)/, "action status should be wired in DOMElements");
assert.match(js, /loginStatus:\s*document\.getElementById\('login-status'\)/, "login status should be wired in DOMElements");
assert.match(js, /connectionStatus:\s*'idle'/, "connection state should be tracked");
assert.match(js, /isLoggingIn:\s*false/, "login submission state should be tracked");
assert.match(js, /isSendingAction:\s*false/, "sending state should be tracked");
assert.match(js, /function setConnectionStatus\(/, "connection status helper should exist");
assert.match(js, /function updateActionControls\(/, "action controls should have a shared availability helper");
assert.match(js, /function formatLoginError\(/, "login errors should be translated into player-facing messages");
assert.match(js, /DOMElements\.loginUsername\.disabled\s*=\s*isBusy/, "username input should be disabled during login submission");
assert.match(js, /DOMElements\.loginInviteCode\.disabled\s*=\s*isBusy/, "invite input should be disabled during login submission");
assert.match(js, /if \(appState\.isLoggingIn\) return;/, "login submission should guard against duplicate submits");
assert.match(js, /请先填写一个道号。/, "blank usernames should get a friendly client-side message");
assert.match(js, /setConnectionStatus\('reconnecting'/, "WebSocket close should surface reconnecting state");
assert.match(js, /WebSocket message error received\./, "server error details should not be shown directly");
assert.match(js, /命运记录暂时无法回应，请稍后再试。/, "server error messages should be player-facing");
assert.match(js, /appState\.isSendingAction\s*=\s*true/, "sending actions should update player-visible state");
assert.doesNotMatch(js, /alert\(/, "player-facing WebSocket errors should not use blocking alerts");
assert.match(js, /if \(daily_success_achieved\) \{\s*return false;\s*\}/s, "daily completion should disable player actions");
assert.match(js, /startButton\.classList\.toggle\('hidden', is_in_trial\)/, "daily completion should leave a stable terminal start button visible and disabled");
assert.match(js, /function toggleStatusPanel\(\)/, "status panel toggle handler should exist");
assert.match(js, /window\.matchMedia\('\(max-width: 850px\)'\)\.matches/, "mobile should start with the status panel collapsed");
assert.match(js, /function scheduleSceneBackgroundUpdate\(\)/, "scene background update should be scheduled after DOM rendering");
assert.match(js, /function updateSceneBackground\(\)/, "scene background updater should exist");
assert.match(js, /requestAnimationFrame\(updateSceneBackground\)/, "scene background should update after a paint frame");
assert.match(js, /addEventListener\('load',\s*scheduleSceneBackgroundUpdate/, "scene background should retry after image load");
assert.match(js, /sceneBackgroundImage:\s*document\.getElementById\('scene-background-image'\)/, "scene background image should be wired in DOMElements");
assert.match(js, /DOMElements\.sceneBackgroundImage\.src\s*=\s*imageUrl/, "scene image URL should be assigned directly to an image element");
assert.doesNotMatch(js, /fullscreenButton/, "fullscreen button wiring should be removed");
